### ISSUE TITLE
BEGIN; - Unable to perform operation using terminated connection.

### ISSUE THREAD

**Issue by iorlenko** [deliverr/data-knex-snowflake-dialect#16]
Connection is getting staled after some inactivity period and knex stops working

**Comment by emurphy** [comment]
This problem applies generally to Snowflake connections on nodejs, see for example: https://community.snowflake.com/s/question/0D50Z00008xA6PESA0/unable-to-perform-operation-using-terminated-connection-using-nodejs-error-unable-to-perform-operation-using-terminated-connection
